dist: trusty
language: node_js
node_js:
  - "10"
before_install:
  - npm link
  - cd ${TRAVIS_BUILD_DIR}/example
  - npm install -g serverless
  - npm link serverless-migrate-plugin
  - npm install
install:
  - echo "Running basic commands"
  - npm run create
  - npm run up
  - npm run down
  - npm run list
  - echo It is all good man!
after_success:
  - cd ..
deploy:
  provider: npm
  email: $NPM_USER
  api_key: $NPM_TOKEN
  edge: true
  on:
    tags: true
    repo: EliuX/serverless-migrate-plugin
